import type { Column } from "../types/column";
import type { User } from "../types/user";

const statusLabel: Record<User["status"], string> = {
  ativo: "Ativo",
  inativo: "Inativo",
  pendente: "Pendente",
};

const dateFormatter = new Intl.DateTimeFormat("pt-BR");

export const users: User[] = [
  {
    id: 1,
    nome: "Ana Beatriz Souza",
    email: "ana.souza@empresa.dev",
    cargo: "admin",
    status: "ativo",
    criadoEm: "2024-02-14",
  },
  {
    id: 2,
    nome: "Bruno Henrique Lima",
    email: "bruno.lima@empresa.dev",
    cargo: "editor",
    status: "ativo",
    criadoEm: "2024-02-20",
  },
  {
    id: 3,
    nome: "Camila Rodrigues Santos",
    email: "camila.santos@empresa.dev",
    cargo: "leitor",
    status: "pendente",
    criadoEm: "2024-03-05",
  },
  {
    id: 4,
    nome: "Daniel Oliveira Costa",
    email: "daniel.costa@empresa.dev",
    cargo: "editor",
    status: "inativo",
    criadoEm: "2024-03-12",
  },
  {
    id: 5,
    nome: "Eduarda Martins Silva",
    email: "eduarda.silva@empresa.dev",
    cargo: "leitor",
    status: "ativo",
    criadoEm: "2024-03-18",
  },
  {
    id: 6,
    nome: "Felipe Augusto Pereira",
    email: "felipe.pereira@empresa.dev",
    cargo: "admin",
    status: "ativo",
    criadoEm: "2024-04-02",
  },
  {
    id: 7,
    nome: "Gabriela Almeida Rocha",
    email: "gabriela.rocha@empresa.dev",
    cargo: "editor",
    status: "pendente",
    criadoEm: "2024-04-10",
  },
  {
    id: 8,
    nome: "Henrique Carvalho Mendes",
    email: "henrique.mendes@empresa.dev",
    cargo: "leitor",
    status: "inativo",
    criadoEm: "2024-04-22",
  },
  {
    id: 9,
    nome: "Isabela Fernandes Dias",
    email: "isabela.dias@empresa.dev",
    cargo: "editor",
    status: "ativo",
    criadoEm: "2024-05-03",
  },
  {
    id: 10,
    nome: "João Pedro Ribeiro",
    email: "joao.ribeiro@empresa.dev",
    cargo: "leitor",
    status: "pendente",
    criadoEm: "2024-05-14",
  },
  {
    id: 11,
    nome: "Karina Lopes Barbosa",
    email: "karina.barbosa@empresa.dev",
    cargo: "admin",
    status: "inativo",
    criadoEm: "2024-05-28",
  },
  {
    id: 12,
    nome: "Lucas Gabriel Araújo",
    email: "lucas.araujo@empresa.dev",
    cargo: "editor",
    status: "ativo",
    criadoEm: "2024-06-06",
  },
  {
    id: 13,
    nome: "Mariana Teixeira Gomes",
    email: "mariana.gomes@empresa.dev",
    cargo: "leitor",
    status: "ativo",
    criadoEm: "2024-06-17",
  },
  {
    id: 14,
    nome: "Nicolas Ferreira Alves",
    email: "nicolas.alves@empresa.dev",
    cargo: "editor",
    status: "pendente",
    criadoEm: "2024-07-01",
  },
  {
    id: 15,
    nome: "Olívia Castro Nunes",
    email: "olivia.nunes@empresa.dev",
    cargo: "leitor",
    status: "inativo",
    criadoEm: "2024-07-09",
  },
  {
    id: 16,
    nome: "Paulo César Moreira",
    email: "paulo.moreira@empresa.dev",
    cargo: "admin",
    status: "ativo",
    criadoEm: "2024-07-23",
  },
  {
    id: 17,
    nome: "Rafaela Batista Monteiro",
    email: "rafaela.monteiro@empresa.dev",
    cargo: "editor",
    status: "inativo",
    criadoEm: "2024-08-05",
  },
  {
    id: 18,
    nome: "Samuel Vieira Cardoso",
    email: "samuel.cardoso@empresa.dev",
    cargo: "leitor",
    status: "ativo",
    criadoEm: "2024-08-16",
  },
  {
    id: 19,
    nome: "Talita Azevedo Freitas",
    email: "talita.freitas@empresa.dev",
    cargo: "editor",
    status: "ativo",
    criadoEm: "2024-09-03",
  },
  {
    id: 20,
    nome: "Vinícius Sales Campos",
    email: "vinicius.campos@empresa.dev",
    cargo: "leitor",
    status: "pendente",
    criadoEm: "2024-09-18",
  },
  {
    id: 21,
    nome: "Yasmin Duarte Melo",
    email: "yasmin.melo@empresa.dev",
    cargo: "admin",
    status: "pendente",
    criadoEm: "2024-10-02",
  },
  {
    id: 22,
    nome: "André Luiz Farias",
    email: "andre.farias@empresa.dev",
    cargo: "editor",
    status: "ativo",
    criadoEm: "2024-10-15",
  },
  {
    id: 23,
    nome: "Bianca Moraes Pinto",
    email: "bianca.pinto@empresa.dev",
    cargo: "leitor",
    status: "inativo",
    criadoEm: "2024-11-07",
  },
  {
    id: 24,
    nome: "Caio Augusto Rezende",
    email: "caio.rezende@empresa.dev",
    cargo: "leitor",
    status: "ativo",
    criadoEm: "2024-11-21",
  },
];

export const columns: Column<User>[] = [
  { key: "nome", title: "Nome", order: true, render: (row) => row.nome },
  { key: "email", title: "E-mail", render: (row) => row.email },
  { key: "cargo", title: "Cargo", order: true, render: (row) => row.cargo },
  {
    key: "status",
    title: "Status",
    render: (row) => (
      <span className={`status status--${row.status}`}>
        {statusLabel[row.status]}
      </span>
    ),
  },
  {
    key: "criadoEm",
    title: "Criado em",
    order: true,
    render: (row) => dateFormatter.format(new Date(row.criadoEm)),
  },
];
